//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07._13_2019_mvc_k30.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class financeDBEntities3 : DbContext
    {
        public financeDBEntities3()
            : base("name=financeDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<OurProject> OurProject { get; set; }
        public virtual DbSet<OurProjectPhoto> OurProjectPhoto { get; set; }
        public virtual DbSet<RecentNewsTB> RecentNewsTB { get; set; }
        public virtual DbSet<Section2Div1> Section2Div1 { get; set; }
        public virtual DbSet<Section2Div2> Section2Div2 { get; set; }
        public virtual DbSet<Section3Div1> Section3Div1 { get; set; }
        public virtual DbSet<Section3Div2> Section3Div2 { get; set; }
        public virtual DbSet<Section4Divs> Section4Divs { get; set; }
        public virtual DbSet<Section5Divs> Section5Divs { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<TopSection1> TopSection1 { get; set; }
    }
}
