//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07._13_2019_mvc_k30.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurProjectPhoto
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
    }
}
