//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07._13_2019_mvc_k30.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecentNewsTB
    {
        public int Id { get; set; }
        public string BlogImage { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public Nullable<int> category_Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Categories Categories1 { get; set; }
    }
}
