//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07._13_2019_mvc_k30.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int Id { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string AdminEmail { get; set; }
        public string AdminPassword { get; set; }
        public string fbLink { get; set; }
        public string instaLink { get; set; }
        public string twitterLink { get; set; }
        public string Logo { get; set; }
    }
}
